#!/usr/bin/env python3
"""
Git 钩子安装脚本
在 Windows 环境下配置 pre-commit 钩子
"""

import os
import sys
import subprocess
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
DOCS_ROOT = SCRIPT_DIR.parent.parent
HOOK_DIR = DOCS_ROOT / ".git" / "hooks"

PRECOMMIT_TEMPLATE = '''#!/usr/bin/env python3
"""
Git pre-commit hook for link checking
Auto-generated by install-git-hook.ps1
"""

import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
CHECKER = SCRIPT_DIR / "check-links.py"
DOCS_ROOT = SCRIPT_DIR.parent / "Docs" / "设定设计"

def main():
    import subprocess

    env = os.environ.copy()
    result = subprocess.run(
        [sys.executable, str(CHECKER), "--fix", "--stage-fixed", "--quiet"],
        cwd=str(DOCS_ROOT),
        capture_output=True,
        text=True,
        env=env
    )

    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr, file=sys.stderr)

    sys.exit(result.returncode)

if __name__ == "__main__":
    main()
'''


def install_hook():
    """安装 Git 钩子"""
    if not HOOK_DIR.exists():
        print(f"Git hooks directory not found: {HOOK_DIR}")
        print("Please make sure this is a git repository.")
        return False

    hook_path = HOOK_DIR / "pre-commit"

    try:
        with open(hook_path, "w", encoding="utf-8") as f:
            f.write(PRECOMMIT_TEMPLATE)

        os.chmod(hook_path, 0o755)
        print(f"Successfully installed pre-commit hook at: {hook_path}")
        return True
    except Exception as e:
        print(f"Failed to install hook: {e}")
        return False


def main():
    print("Installing Git pre-commit hook for link checking...")
    print(f"Hook directory: {HOOK_DIR}")
    print(f"Scripts directory: {SCRIPT_DIR}")
    print("-" * 60)

    success = install_hook()

    if success:
        print("-" * 60)
        print("Installation successful!")
        print("The hook will run check-links.py before each commit.")
    else:
        print("-" * 60)
        print("Installation failed. Please check permissions.")
        sys.exit(1)


if __name__ == "__main__":
    main()
